general:
    build-channel: 'dev'
    elements-per-page: 10
    help-format: '&b    {0}'
    server-name: '&8SimpleClans'
    global-ff: false
    auto-save: 5
    reporting:
        errors: true
        email: ''
commands:
    clan: 'clan'
    rank: 'rank'
    bb: 'bb'
    bank: 'bank'
database:
    mode: 'mysql'
    host: 'localhost'
    port: 3306
    username: 'root'
    password: ''
    database: 'sc'
teleportation:
    drop-items-on-teleport: false
    drop-all-items-on-teleport: false
    keep-items-on-teleport: [ ]
    teleport-fuzzyness: 1.5
    teleport-waiting-time: 10
pvp:
    only-pvp-in-war: false
    save-civilians: true
    global-ff-forced: false
    weights:
        rival: 2
        neutral: 1
        civilian: 1
clan:
   max-tag-lenght: 3
   min-tag-lenght: 3
   max-name-lenght: 15
   min-name-lenght: 5
   set-home-only-once: false
   minimal-size-to-ally: 1
   minimal-size-to-rival: 1
   rival-limit-percent: 20
   require-verification: true
   purge:
       inactive-player-data-days: 30
       inactive-clan-days: 7
       unverified-clan-days: 2
   bb:
       clan: '&8* +clan: &b+message'
       clanplayer: '&8* +player: &b+message'
       default: '&8* &b+message'
       max-lines: 3000
       max-display-lines: 10
   announce:
       clan: '+clan: +message'
       clanplayer: '+player: +message'
       default: '+message'
   economy:
       purchase-creation: 20
       purchase-teleport: -1
   voting:
       demote: true
       promote: true
   spout:
       capes:
           default: 'http://dl.dropbox.com/u/20831395/simpleclans/cape.png'
           enabled: true
   motd:
       bb: true
       lines: 5
       format: '&4- -%s'
   unrivalable-clans: [ ]
   modify-tag-completely: false
paging:
   colors:
       heading-color: '8'
       sub-color: '7'
       clan-color: 'b'
       leader-color: '4'
       trusted-color: 'f'
       untrusted-color: '8'
