general:
    elements-per-page: 10
    clan-command: clan
    server-name: SimpleClans
    global-ff: false
    auto-save: 5
teleportation:
    drop-items-on-teleport: false
    drop-all-items-on-teleport: false
    keep-items-on-teleport: [ ]
    teleport-fuzzyness: 1.5
    teleport-waiting-time: 10
pvp:
    only-pvp-in-war: false
    save-civilians: true
    global-ff-forced: false
    weights:
        rival: 2
        neutral: 1
        civilian: 1
clan:
   max-tag-lenght: 3
   min-tag-lenght: 3
   max-name-lenght: 15
   min-name-lenght: 5
   set-home-only-once: false
   minimal-size-to-ally: 1
   purge:
       inactive-player-data-days: 30
       inactive-clan-days: 7
       unverified-clan-days: 2
   bb:
       clan: '+clan: +message'
       clanplayer: '+player: +message'
       default: '+message'
       max-lines: 1000
       max-display-lines: 10
   announce:
       clan: '+clan: +message'
       clanplayer: '+player: +message'
       default: '+message'
   economy:
       purchase-creation: 20
       purchase-teleport: -1
   voting:
       demote: true
   capes:
       default: 'http://dl.dropbox.com/u/20831395/simpleclans/cape.png'
       enabled: true
   motd:
       bb: true
       lines: 5
       format: '&4- -bb'
paging:
   colors:
       heading-color: '8'
       sub-color: '7'
       clan-color: 'b'
       leader-color: '4'
       trusted-color: 'f'
       untrusted-color: '8'
