name: SimpleClans2
main: com.p000ison.dev.simpleclans2.SimpleClans
version: unknown-version
commands:
  sc:
  rank:
  bb:
permissions:
  simpleclans.admin.permissions:
    description: Can grant clans permissions
  simpleclans.admin.reload:
    description: Can reload configuration
  simpleclans.admin.all-seeing-eye:
    description: Can see all clan chats
  simpleclans.mod.verify:
    description: Can verify simpleclans
  simpleclans.mod.ban:
    description: Can ban players from the entire plugin
  simpleclans.mod.unban:
    description: Can unban players from the entire plugin
  simpleclans.mod.disband:
    description: Can disband any clan
  simpleclans.mod.globalff:
    description: Can turn off global friendly fire protection
  simpleclans.mod.nohide:
    description: Messages from these players cannot be hidden via chat commands
  simpleclans.mod.home:
    description: Can set other clan's home
  simpleclans.mod.bypass:
    description: Can bypass restrictions
  simpleclans.mod.nopvpinwar:
    description: Can bypass pvp in wars
  simpleclans.anyone.list:
    description: Can list simpleclans
  simpleclans.anyone.profile:
    description: Can view a clan's profile
  simpleclans.anyone.roster:
    description: Can veiw a clan's member list
  simpleclans.anyone.lookup:
    description: Can lookup a player's info
  simpleclans.anyone.leaderboard:
    description: Can view the leaderboard
  simpleclans.anyone.alliances:
    description: Can view alliances by clan
  simpleclans.anyone.rivalries:
    description: Can view rivalries by clan
  simpleclans.member.profile:
    description: Can view his own clan's profile
  simpleclans.member.roster:
    description: Can view his own clan's member list
  simpleclans.member.lookup:
    description: Can view his own player info
  simpleclans.member.vitals:
    description: Can view his clan's vitals
  simpleclans.member.coords:
    description: Can view his clan's coords
  simpleclans.member.stats:
    description: Can view his simpleclans stats
  simpleclans.member.bb:
    description: Can view his clan's bulletin board
  simpleclans.member.bb-add:
    description: Can add to his clan's bulletin board
  simpleclans.member.bb-clear:
    description: Can clear the bulletin board
  simpleclans.member.toggle.bb:
    description: Can toggle bb on/off
  simpleclans.member.ff:
    description: Can toggle his own friendly fire
  simpleclans.member.resign:
    description: Can resign from his clan
  simpleclans.member.ally:
    description: Can use ally chat
  simpleclans.member.can-join:
    description: Can join clans
  simpleclans.member.home:
    description: Can tp to home base
  simpleclans.leader.create:
    description: Can create simpleclans
  simpleclans.leader.home-set:
    description: Can set home base
  simpleclans.leader.home-regroup:
    description: Can tp entire clan to homebase
  simpleclans.leader.ally:
    description: Can ally his clan with other simpleclans
  simpleclans.leader.rival:
    description: Can start a rivalry with another clan
  simpleclans.leader.modtag:
    description: Can modify his clan's tag
  simpleclans.leader.cape:
    description: Can set his clan's cape url
  simpleclans.member.toggle.cape:
    description: Can toggle his cape on/off
  simpleclans.member.kills:
    description: Can view his and other's kills
  simpleclans.mod.mostkilled:
    description: Can view his and other's clans mostkilled
  simpleclans.mod.keep-items:
    description: Can keep items when teleporting home
  simpleclans.leader.invite:
    description: Can invite players into his clan
  simpleclans.leader.kick:
    description: Can kick players form his tea,
  simpleclans.leader.promote:
    description: Can promote players to clan leaders
  simpleclans.leader.promotable:
    description: Can be promoted to clan leader
  simpleclans.leader.demote:
    description: Can demote clan leaders to normal players
  simpleclans.leader.ff:
    description: Can toggle his clan's friendly fire
  simpleclans.leader.disband:
    description: Can disband his own clan
  simpleclans.leader.settrust:
    description: Can set trust levels for members
  simpleclans.leader.war:
    description: Can start wars
  simpleclans.leader.setrank:
    description: Can set ranks
  simpleclans.admin.convert:
    description: Can convert from old versions
  simpleclans.admin.info:
    description: Can view information about SC
  simpleclans.admin.save:
    description: Can force a save
  simpleclans.admin.upgrade:
    description: Can upgrade the plugin
  simpleclans.member.bank.balance:
    description: Can view the balance of the clan
  simpleclans.member.bank.deposit:
    description: Can deposit money in the clan bank
  simpleclans.member.bank.withdraw:
    description: Can withdraw money from the clan bank
  simpleclans.leader.rank.permissions.add:
    description: Can add permissions to a rank
  simpleclans.leader.rank.permissions.remove:
    description: Can remove permissions from a rank
  simpleclans.leader.rank.permissions.list:
    description: Can list all available permissions
  simpleclans.leader.rank.create:
    description: Can create a new rank
  simpleclans.leader.rank.delete:
    description: Can delete a new rank
  simpleclans.leader.rank.detail:
    description: Can view details about a rank
  simpleclans.leader.rank.assign:
    description: Can assign a rank to a user
  simpleclans.leader.rank.list:
    description: Can list all the ranks
  simpleclans.member.accept:
    description: Can accept
  simpleclans.member.deny:
    description: Can deny
  simpleclans.member.abstain:
    description: Can abstain
  simpleclans.mod.*:
    description: Permissions for moderators
    default: op
    children:
      simpleclans.mod.verify: true
      simpleclans.mod.ban: true
      simpleclans.mod.disband: true
      simpleclans.mod.globalff: true
      simpleclans.mod.bypass: true
      simpleclans.mod.home: true
      simpleclans.mod.mostkilled: true
      simpleclans.mod.keep-items: true
      simpleclans.mod.nopvpinwar: true
      simpleclans.mod.unban: true
  simpleclans.anyone.*:
    description: Permissions for anyone
    default: true
    children:
      simpleclans.anyone.list: true
      simpleclans.anyone.profile: true
      simpleclans.anyone.roster: true
      simpleclans.anyone.lookup: true
      simpleclans.anyone.leaderboard: true
      simpleclans.anyone.alliances: true
      simpleclans.anyone.rivalries: true
      simpleclans.anyone.kills: true
  simpleclans.member.*:
    description: Permissions for those who can be clan members
    default: false
    children:
      simpleclans.anyone.*: true
      simpleclans.member.can-join: true
      simpleclans.member.profile: true
      simpleclans.member.roster: true
      simpleclans.member.lookup: true
      simpleclans.member.vitals: true
      simpleclans.member.coords: true
      simpleclans.member.stats: true
      simpleclans.member.bb: true
      simpleclans.member.bb-add: true
      simpleclans.member.toggle.bb: true
      simpleclans.member.toggle.cape: true
      simpleclans.member.ff: true
      simpleclans.member.resign: true
      simpleclans.member.ally: true
      simpleclans.member.home: true
      simpleclans.member.kills: true
      simpleclans.member.bank: true
      simpleclans.member.accept: true
      simpleclans.member.deny: true
      simpleclans.member.abstain: true
      simpleclans.member.bank.balance: true
      simpleclans.member.bank.deposit: true
      simpleclans.member.bank.withdraw: true
  simpleclans.leader.*:
    description: Permissions for those who can be clan leaders
    default: false
    children:
      simpleclans.member.*: true
      simpleclans.leader.create: true
      simpleclans.leader.ally: true
      simpleclans.leader.rival: true
      simpleclans.leader.modtag: true
      simpleclans.leader.cape: true
      simpleclans.leader.invite: true
      simpleclans.leader.kick: true
      simpleclans.leader.promote: true
      simpleclans.leader.promotable: true
      simpleclans.leader.demote: true
      simpleclans.leader.ff: true
      simpleclans.leader.disband: true
      simpleclans.leader.settrust: true
      simpleclans.leader.war: true
      simpleclans.leader.home-set: true
      simpleclans.leader.home-regroup: true
      simpleclans.leader.setrank: true
      simpleclans.leader.rank.permissions.add: true
      simpleclans.leader.rank.permissions.remove: true
      simpleclans.leader.rank.permissions.list: true
      simpleclans.leader.rank.create: true
      simpleclans.leader.rank.delete: true
      simpleclans.leader.rank.detail: true
      simpleclans.leader.rank.set: true
      simpleclans.leader.rank.list: true
  simpleclans.admin.*:
    description: Permissions for admins
    default: op
    children:
      simpleclans.leader.*: true
      simpleclans.admin.reload: true
      simpleclans.admin.all-seeing-eye: true
      simpleclans.admin.convert: true
      simpleclans.admin.info: true
      simpleclans.admin.save: true
      simpleclans.admin.upgrade: true