settings:
   compatibility-mode: false
   cancelling-mode: false
   complete-mode: true
   depreciation-mode: false
format:
   complete-mode: '-clan-group-prefix-player: -message'
   variables:
       clan: '[%s]'
       group: '[%s]'
       prefix: '[%s]'
       suffix: '[%s]'
       player: '[%s]'
       rank: '[%s]'
channels:
   clan: '[CLAN]-rank-player -message'
   ally: '[ALLY]-player -message'
