name: SimpleClansChat
main: com.p000ison.dev.simpleclans2.chat.SimpleClansChat
version: maven-version-number
commands:
  scc:
  ally:
  .:
  global:
depends: [ SimpleClans ]
softdepend: [ ChatSuite, Herochat ]